sudo: false
language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
cache: pip
services:
- mongodb
script:
- python -m flake8
- mypy mongots --ignore-missing-imports
- python -m pytest --cov=mongots
after_success:
- coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: toubi
  password:
    secure: QoxmfWbnj+kVUJVyRjN4UVfK9mRQGq5+UeDjqe3L5IotOgzZtky6I3dpKk2vDThKUjyH0fvZizyszxM7wOtmogIIG8YCrsUQecv+GoSM+qmbrApg2ggtE0eNH19yOtHf2nPH8FP3B+YIu2rRtxAJKrka3w0R7KHk3D+TeKBuwGQYloj2vQXaxD04JZRwQwN0Od8xBwdNtVSlu3qcSyfSQPqsWWuDaufMRuqKShTI1VpNHr29Lchi+CucD7B2i91TgklzmWUdvZmF2Nz4lcs/b8I2Fb65TsMHMTLrP4qQ+uX92yITolm7i5w+lGG8UfUEu+fCcdPbCu/Z8fgBB7vu422NM5A1j1BQYoA7yQ3nHUs70upduyHoOAhQoW/mFXB6kbBjSwAhhsBTx7j54Q7QzKYI4POpy07hPZOcP9fb1ofOdmVsxSpqsl0d+Jc/hZZOcXbg6mtY1/N5mafBhILABddejq02xPPvxl4EBVCWCin+UIbn77IxheymUrnbXGNdIN6ysnslxGXQjSORIFF/ELthZKaKhS7ptitARBQ52FiM/NCHLQht68JpagQoEG73yXP6qDl2Z+m6EEwXlgfCPttFFltzHalm9+pcEJg7nOkKaRbEDfyEduGzOiWuyCVm71LfYkQohyIUNwBoR/C4KCja8v+JBY7+2QuQOhOchdI=
  on:
    python: 3.6
    repo: AntoineToubhans/MongoTs
    tags: true
    branch: master
